# Generated by Django 4.2.9 on 2024-11-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default='2024-11-10T15:25:43.742694+00:00'),
        ),
    ]
