# Generated by Django 4.2.9 on 2024-11-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0029_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default='2024-11-16T04:38:16.649968+00:00'),
        ),
    ]
