# Generated by Django 4.2.9 on 2024-11-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0039_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default='2024-11-16T06:39:41.181161+00:00'),
        ),
    ]
