# Generated by Django 4.2.9 on 2024-11-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0046_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default='2024-11-16T08:55:01.452681+00:00'),
        ),
    ]
