# Generated by Django 4.2.9 on 2024-11-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0055_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default='2024-11-16T09:01:38.857464+00:00'),
        ),
    ]
