# Generated by Django 4.2.9 on 2024-11-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0058_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default='2024-11-16T09:02:31.916144+00:00'),
        ),
    ]
