# Generated by Django 4.2.9 on 2024-11-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0083_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default='2024-11-16T16:44:33.394258+00:00'),
        ),
    ]
