# Generated by Django 4.2.9 on 2024-11-07 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lot.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='lot.category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used - Excellent', 'Used Excellent'), ('Used - Good', 'Used Good'), ('Used - Fair', 'Used Fair'), ('Used - Poor', 'Used Poor')], default='New', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('starting_price', models.PositiveIntegerField()),
                ('buy_it_now_price', models.PositiveIntegerField(blank=True, null=True)),
                ('reserve_price', models.PositiveIntegerField(blank=True, null=True)),
                ('auction_start_time', models.DateTimeField(blank=True, null=True)),
                ('auction_duration', models.IntegerField(choices=[(2, 'Two Days'), (3, 'Three Days'), (5, 'Five Days'), (7, 'Seven Days'), (10, 'Ten Days')], default=2)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_auction_over', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='lot.category')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorite_lots', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LotShippingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_status', to='lot.lot')),
            ],
        ),
        migrations.CreateModel(
            name='LotShippingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('Box', 'Box'), ('Envelope', 'Envelope')], max_length=50)),
                ('dimensions', models.CharField(max_length=50)),
                ('weight', models.CharField(choices=[('0-2', 'Upto 2 Kg'), ('2-5', 'Upto 5 Kg'), ('5-10', 'Upto 10 Kg'), ('10-20', 'Upto 20 Kg')], max_length=50)),
                ('item_location', models.CharField(max_length=100)),
                ('carrier', models.CharField(choices=[('0-2', 'Upto 2 Kg'), ('2-5', 'Upto 5 Kg'), ('5-10', 'Upto 10 Kg'), ('10-20', 'Upto 20 Kg')], max_length=50)),
                ('shipment_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('shipping_notes', models.TextField(blank=True, null=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotShippingDetails', to='lot.lot')),
            ],
        ),
        migrations.CreateModel(
            name='LotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=lot.utils.rename_image)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotImages', to='lot.lot')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('bidded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted', models.BooleanField(default=False)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='lot.lot')),
            ],
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['id', 'slug'], name='lot_lot_id_542dd2_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['name'], name='lot_lot_name_e308e5_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['-created'], name='lot_lot_created_622a33_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='lot_categor_name_2de101_idx'),
        ),
    ]
